openapi: 3.0.1
info:
  title: darius-backend
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: fee
- name: bot
- name: general
paths:
  /health_liveness:
    get:
      tags:
      - general
      summary: Return a 200 status if health check is successful
      operationId: main.src.controllers.v1.general.get_health_liveness
      responses:
        200:
          description: Liveness Health check is successful
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
        default:
          $ref: '#/components/responses/Unexpected'
          
  /health_readiness:
    get:
      tags:
      - general
      summary: Return a 200 status if health check is successful
      operationId: main.src.controllers.v1.general.get_health_readiness
      responses:
        200:
          description: Readiness Health check is successful
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
        default:
          $ref: '#/components/responses/Unexpected'

  /create_test_data:
    get:
      tags:
      - general
      summary: create test data in database
      operationId: main.src.controllers.v1.general.create_test_data
      responses:
        '200':
          description: received
        default:
          $ref: '#/components/responses/Unexpected'
  
  /bot_signal:
    post:
      tags:
      - bot
      summary: recieve signal info and make orders
      operationId: main.src.controllers.v1.bot.bot_signal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                channel:
                  type: string
                content:
                  type: string
                  nullable: true
                message_timestamp:
                  type: number
                recieve_timestamp:
                  type: number
                symbol:
                  type: string
                  nullable: true
                  maxLength: 16
                action:
                  $ref: '#/components/schemas/Action'
              required:
              - channel
              - content
              - message_timestamp
              - recieve_timestamp
              - symbol
              - action
      responses:
        '200':
          description: received
        default:
          $ref: '#/components/responses/Unexpected'
  
  /user_confirm_payment:
    post:
      tags:
      - fee
      summary: give payment confirmation results and new due date
      operationId: main.src.controllers.v1.fee.user_confirm_payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                # add
              required:
              - user_id
      responses:
        '200':
          description: give payment confirmation results
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                required:
                - status
        '400':
          description: The specified user ID is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'


  /get_user_due_date:
    post:
      tags:
      - fee
      summary: get user due date
      operationId: main.src.controllers.v1.fee.get_user_due_date
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                # add
              required:
              - user_id
            example:
              user_id: 0
      responses:
        '200':
          description: Get user due date.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  timestamp:
                    type: number
                required:
                - timestamp
        '400':
          description: The specified user ID is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/Unexpected'
          
components:

  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unexpected:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      required:
      - message
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
    ExtendedError:
      allOf:
      - $ref: '#/components/schemas/Error'
      - type: object
        required:
        - rootCause
        properties:
          rootCause:
            type: string
    Action:
      type: string
      nullable: true
      enum:
        - BUY
        - SELL
        - null
